### PR TITLE
Use manual string splitting rather than regex to build fileName

### LINKED ISSUE #8: Runner ignores errors in test files
When checked via the runner I get no errors but when running `flow` directly I get the correct errors

### PR DESCRIPTION
**Pull request by slightlytyler**
fixes #8

This might not be the best way to handle it, what do you think?

### CODE REVIEW

**Comment by binygal** [comment]
This was my initial implementation but I had a suggestion to change it. (https://github.com/binygal/jest-runner-flowtype/pull/3#pullrequestreview-105438260)
I think that we can just extend the  regex to support dot as part of file name (or directory) like that - `(\.{1,2}|\/)?([A-z]|\/|-|\.)*\.js(x?)`
What do you think?

**Comment by slightlytyler** [comment]
@binygal I'm not familiar with the expected range of inputs but can try changing the RegEx. Figured the manual splitting would not be general enough to actually work 😉

**Comment by binygal** [comment]
The accepted range is a js/jsx file path, absolute or relative. Right now it accepts only files folders with letters or dash in the path. My suggestion adds the dot, you can take it and digits or whatever character that make sense in file/folder names.

**Comment by slightlytyler** [comment]
@binygal ok I've updated it to use the pattern you suggested. If you think it's sufficient would love to get this merged 👍

**Comment by binygal** [comment]
This PR was created against the `initial` branch 😃I've rebased it against master and pushed the changes. 
@slightlytyler Thank you for contributing!

**Pull request merged**
